// lib/wineries-data.ts
import { Winery } from '@/types/winery';

export const wineries: Winery[] = [
  {
    id: "1",
    name: "MountainRose Vineyards",
    street: "10439 N. Reservoir Rd.",
    city: "Wise",
    state: "VA",
    zip: "24293",
    phone: "276-328-2013",
    website: "mountainrosevineyard.com",
    region: "Heart of Appalachia"
  },
  {
    id: "2",
    name: "Vincent's Vineyard",
    street: "2313 E. Main St.",
    city: "Lebanon",
    state: "VA",
    zip: "24266",
    phone: "276-219-4522",
    website: "vincentsvineyard.com",
    region: "Heart of Appalachia"
  },
  {
    id: "3",
    name: "Breezy Hill Meadworks",
    street: "15981 Breezy Hill Ln.",
    city: "Smithfield",
    state: "VA",
    zip: "23430",
    phone: "757-214-7494",
    website: "breezyhillmeadworks.com",
    region: "Hampton Roads"
  },
  {
    id: "4",
    name: "Gauthier Vineyard",
    street: "5000 Farmers Dr.",
    city: "Barhamsville",
    state: "VA",
    zip: "23011",
    phone: "757-350-3125",
    website: "gauthiervineyard.com",
    region: "Hampton Roads"
  },
  {
    id: "5",
    name: "Hampton Roads Winery",
    street: "6074 New Design Rd.",
    city: "Elberon",
    state: "VA",
    zip: "23846",
    phone: "757-899-0203",
    website: "hamptonroadswinery.com",
    region: "Hampton Roads"
  },
  {
    id: "6",
    name: "Jolene Family Winery",
    street: "2750 Pocahontas Tr.",
    city: "Quinton",
    state: "VA",
    zip: "23141",
    phone: "804-557-5316",
    website: "jolenefamilywinery.com",
    region: "Hampton Roads"
  },
  {
    id: "7",
    name: "Mermaid Winery",
    street: "101 Granby St.",
    city: "Norfolk",
    state: "VA",
    zip: "23510",
    phone: "757-233-4155",
    website: "mermaidwinery.com",
    region: "Hampton Roads"
  },
  {
    id: "8",
    name: "New Kent Winery",
    street: "8400 Old Church Rd.",
    city: "New Kent",
    state: "VA",
    zip: "23124",
    phone: "804-922-7414",
    website: "newkentwinery.com",
    region: "Hampton Roads"
  },
  {
    id: "9",
    name: "Saudé Creek Vineyards",
    street: "16230 Cooks Mill Rd.",
    city: "Lanexa",
    state: "VA",
    zip: "23089",
    phone: "804-966-5896",
    website: "saudecreek.com",
    region: "Hampton Roads"
  },
  {
    id: "10",
    name: "Sly Clyde Ciderworks",
    street: "207 E. Mellen St.",
    city: "Hampton",
    state: "VA",
    zip: "23663",
    phone: "amelia@slyclyde.com",
    website: "slyclyde.com",
    region: "Hampton Roads"
  },
  {
    id: "11",
    name: "Smithfield Winery",
    street: "117 N. Church St.",
    city: "Smithfield",
    state: "VA",
    zip: "23430",
    phone: "757-797-9463",
    website: "smithfieldwinery.com",
    region: "Hampton Roads"
  },
  {
    id: "12",
    name: "SummerWind Vineyard",
    street: "71 Eagle Nest Ln.",
    city: "Smithfield",
    state: "VA",
    zip: "23430",
    phone: "757-357-2173",
    website: "swvsmithfield.com",
    region: "Hampton Roads"
  },
  {
    id: "13",
    name: "Upper Shirley Vineyards",
    street: "600 Shirley Plantation Rd.",
    city: "Charles City",
    state: "VA",
    zip: "23030",
    phone: "804-829-9463",
    website: "uppershirley.com",
    region: "Hampton Roads"
  },
  {
    id: "14",
    name: "Williamsburg Winery",
    street: "5800 Wessex Hundred",
    city: "Williamsburg",
    state: "VA",
    zip: "23185",
    phone: "757-229-0999",
    website: "williamsburgwinery.com",
    region: "Hampton Roads"
  },
  {
    id: "15",
    name: "Chatham Vineyards on Church Creek",
    street: "9232 Chatham Rd.",
    city: "Machipongo",
    state: "VA",
    zip: "23405",
    phone: "757-678-5588",
    website: "chathamvineyards.com",
    region: "Eastern Shore"
  },
  {
    id: "16",
    name: "Backporch Vineyard",
    street: "16595 Wilmont Rd.",
    city: "King George",
    state: "VA",
    zip: "22485",
    phone: "540-940-3939",
    website: "backporchvineyard.com",
    region: "Chesapeake Bay"
  },
  {
    id: "17",
    name: "Caret Cellars",
    street: "495 Meadow Landing Ln.",
    city: "Caret",
    state: "VA",
    zip: "22436",
    phone: "540-413-6454",
    website: "caretcellars.com",
    region: "Chesapeake Bay"
  },
  {
    id: "18",
    name: "Ditchley Cider Works",
    street: "1571 Ditchley Rd.",
    city: "Kilmarnock",
    state: "VA",
    zip: "22482",
    phone: "804-435-3851",
    website: "ditchleyciderworks.com",
    region: "Chesapeake Bay"
  },
  {
    id: "19",
    name: "General's Ridge Vineyard",
    street: "1618 Weldons Dr.",
    city: "Hague",
    state: "VA",
    zip: "22469",
    phone: "804-472-3172",
    website: "generalsridgevineyard.com",
    region: "Chesapeake Bay"
  },
  {
    id: "20",
    name: "Good Luck Cellars",
    street: "1025 Good Luck Rd.",
    city: "Kilmarnock",
    state: "VA",
    zip: "22482",
    phone: "804-435-1416",
    website: "goodluckcellars.com",
    region: "Chesapeake Bay"
  },
  {
    id: "21",
    name: "Ingleside Vineyards",
    street: "5872 Leedstown Rd.",
    city: "Oak Grove",
    state: "VA",
    zip: "22443",
    phone: "804-224-8687",
    website: "inglesidevineyards.com",
    region: "Chesapeake Bay"
  },
  {
    id: "22",
    name: "Jacey Vineyards",
    street: "619 Train Ln.",
    city: "Heathsville",
    state: "VA",
    zip: "22473",
    phone: "804-580-4053",
    website: "jaceyvineyard.com",
    region: "Chesapeake Bay"
  },
  {
    id: "23",
    name: "Mattapony Reserve",
    street: "1581 Mattaponi Reservation Cir.",
    city: "West Point",
    state: "VA",
    zip: "23181",
    phone: "",
    website: "mattaponyreserve.info",
    region: "Chesapeake Bay"
  },
  {
    id: "24",
    name: "Monroe Bay Winery",
    street: "4786 James Monroe Hwy.",
    city: "Colonial Beach",
    state: "VA",
    zip: "22443",
    phone: "804-410-5628",
    website: "monroebaywine.com",
    region: "Chesapeake Bay"
  },
  {
    id: "25",
    name: "Rivah Vineyards at The Grove",
    street: "671 Kinsale Bridge Rd.",
    city: "Kinsale",
    state: "VA",
    zip: "22488",
    phone: "804-599-8552",
    website: "rivahvineyards.com",
    region: "Chesapeake Bay"
  },
  {
    id: "26",
    name: "The Estate at White Hall Vineyard",
    street: "3668 White Hall Rd.",
    city: "King George",
    state: "VA",
    zip: "22485",
    phone: "540-656-6958",
    website: "theestateatwhitehall.com",
    region: "Chesapeake Bay"
  },
  {
    id: "27",
    name: "The Hague Winery",
    street: "8268 Cople Hwy.",
    city: "Hague",
    state: "VA",
    zip: "22469",
    phone: "804-472-5283",
    website: "thehaguewinery.com",
    region: "Chesapeake Bay"
  },
  {
    id: "28",
    name: "Triple V Farms",
    street: "3138 Jessie DuPont Memorial Hwy.",
    city: "Heathsville",
    state: "VA",
    zip: "22473",
    phone: "804-724-5765",
    website: "triplevfarms.com",
    region: "Chesapeake Bay"
  },
  {
    id: "29",
    name: "Wind Vineyards at Laurel Grove",
    street: "5178 Richmond Hwy.",
    city: "Tappahannock",
    state: "VA",
    zip: "22560",
    phone: "804-238-5544",
    website: "windvineyards.com",
    region: "Chesapeake Bay"
  },
  {
    id: "30",
    name: "Zoll Vineyards",
    street: "10309 Vineyard Rd.",
    city: "Dutton",
    state: "VA",
    zip: "23050",
    phone: "774-275-7581",
    website: "zollvineyards.com",
    region: "Chesapeake Bay"
  },
  {
    id: "31",
    name: "7 Lady Vineyards",
    street: "1500 Manakin Rd.",
    city: "Manakin-Sabot",
    state: "VA",
    zip: "23103",
    phone: "804-784-6051 ext: 4",
    website: "7ladyvineyards.com",
    region: "Central Virginia"
  },
  {
    id: "32",
    name: "Afton Mountain Vineyards",
    street: "234 Vineyard Ln.",
    city: "Afton",
    state: "VA",
    zip: "22920",
    phone: "540-456-8667",
    website: "aftonmountainvineyards.com",
    region: "Central Virginia"
  },
  {
    id: "33",
    name: "Albemarle CiderWorks",
    street: "2545 Rural Ridge Ln.",
    city: "North Garden",
    state: "VA",
    zip: "22959",
    phone: "434-297-2326",
    website: "albemarleciderworks.com",
    region: "Central Virginia"
  },
  {
    id: "34",
    name: "Ankida Ridge Vineyards",
    street: "1304 Franklin Creek Rd.",
    city: "Amherst",
    state: "VA",
    zip: "24521",
    phone: "434-922-7678",
    website: "ankidaridge.com",
    region: "Central Virginia"
  },
  {
    id: "35",
    name: "Ashton Creek Vineyard and Winery",
    street: "14501 Jefferson Davis Hwy.",
    city: "Chester",
    state: "VA",
    zip: "23831",
    phone: "804-896-1586",
    website: "ashtoncreekvineyard.com",
    region: "Central Virginia"
  },
  {
    id: "36",
    name: "Barboursville Vineyards",
    street: "17655 Winery Rd.",
    city: "Barboursville",
    state: "VA",
    zip: "22923",
    phone: "540-832-3824",
    website: "bbvwine.com",
    region: "Central Virginia"
  },
  {
    id: "37",
    name: "Barn at 678",
    street: "6045 Governor Barbour St.",
    city: "Barboursville",
    state: "VA",
    zip: "22923",
    phone: "434-981-3793",
    website: "barnat678.com",
    region: "Central Virginia"
  },
  {
    id: "38",
    name: "Black Heath Meadery",
    street: "1313 Altamont Ave.",
    city: "Richmond",
    state: "VA",
    zip: "23230",
    phone: "804-998-7090",
    website: "blackheathmeadery.com",
    region: "Central Virginia"
  },
  {
    id: "39",
    name: "Blenheim Vineyards",
    street: "31 Blenheim Farm",
    city: "Charlottesville",
    state: "VA",
    zip: "22902",
    phone: "434-293-5366",
    website: "blenheimvineyards.com",
    region: "Central Virginia"
  },
  {
    id: "40",
    name: "Blue Bee Cider",
    street: "4811 Bethlehem Rd. Ste. A",
    city: "Richmond",
    state: "VA",
    zip: "23230",
    phone: "804-231-0280",
    website: "bluebeecider.com",
    region: "Central Virginia"
  },
  {
    id: "41",
    name: "Blue Quartz Winery",
    street: "2585 S F T Valley Rd.",
    city: "Etlan",
    state: "VA",
    zip: "22719",
    phone: "540-923-4048",
    website: "bluequartzwinery.com",
    region: "Central Virginia"
  },
  {
    id: "42",
    name: "Blue Toad Hard Cider",
    street: "462 Winery Ln.",
    city: "Roseland",
    state: "VA",
    zip: "22967",
    phone: "434-760-9200",
    website: "bluetoadhardcider.com",
    region: "Central Virginia"
  },
  {
    id: "43",
    name: "Bold Rock Hard Cider",
    street: "1020 Rockfish Valley Hwy.",
    city: "Nellysford",
    state: "VA",
    zip: "22958",
    phone: "434-361-1030",
    website: "boldrock.com",
    region: "Central Virginia"
  },
  {
    id: "44",
    name: "Brent Manor Vineyards",
    street: "100 Brent Manor Ln.",
    city: "Faber",
    state: "VA",
    zip: "22938",
    phone: "434-826-0722",
    website: "brentmanorvineyards.com",
    region: "Central Virginia"
  },
  {
    id: "45",
    name: "Bryant's Cider",
    street: "3224 E. Branch Loop",
    city: "Roseland",
    state: "VA",
    zip: "22967",
    phone: "804-799-0401",
    website: "bryantscider.com",
    region: "Central Virginia"
  },
  {
    id: "46",
    name: "Burnley Vineyards",
    street: "4500 Winery Ln.",
    city: "Barboursville",
    state: "VA",
    zip: "22923",
    phone: "434-906-0173",
    website: "burnleywines.com",
    region: "Central Virginia"
  },
  {
    id: "47",
    name: "Buskey Cider",
    street: "2910 W. Leigh St.",
    city: "Richmond",
    state: "VA",
    zip: "23230",
    phone: "804-355-0100",
    website: "buskeycider.com",
    region: "Central Virginia"
  },
  {
    id: "48",
    name: "Byrd Cellars",
    street: "2442 Davis Mill Rd.",
    city: "Goochland",
    state: "VA",
    zip: "23063",
    phone: "804-652-5663",
    website: "byrdcellars.com",
    region: "Central Virginia"
  },
  {
    id: "49",
    name: "Caihailian Vineyard",
    street: "872 Beech Grove Rd.",
    city: "Roseland",
    state: "VA",
    zip: "22967",
    phone: "571-643-1692",
    website: "chivineyard.com",
    region: "Central Virginia"
  },
  {
    id: "50",
    name: "Cardinal Point Vineyard & Winery",
    street: "9423 Batesville Rd.",
    city: "Afton",
    state: "VA",
    zip: "22920",
    phone: "540-456-8400",
    website: "cardinalpointwinery.com",
    region: "Central Virginia"
  },
  {
    id: "51",
    name: "Castle Glen Winery",
    street: "18185 Narrow Path Tr.",
    city: "Doswell",
    state: "VA",
    zip: "23047",
    phone: "804-763-9677",
    website: "castleglenwine.com",
    region: "Central Virginia"
  },
  {
    id: "52",
    name: "Castle Hill Cider",
    street: "6065 Turkey Sag Rd.",
    city: "Keswick",
    state: "VA",
    zip: "22947",
    phone: "434-296-0047",
    website: "castlehillcider.com",
    region: "Central Virginia"
  },
  {
    id: "53",
    name: "Chateau MerrillAnne",
    street: "16234 Marquis Rd.",
    city: "Orange",
    state: "VA",
    zip: "22960",
    phone: "540-656-6177",
    website: "chateaumerrillanne.com",
    region: "Central Virginia"
  },
  {
    id: "54",
    name: "Chestnut Oak Vineyard",
    street: "5050 Stony Point Rd.",
    city: "Barboursville",
    state: "VA",
    zip: "22923",
    phone: "434-964-9104",
    website: "chestnutoakvineyard.com",
    region: "Central Virginia"
  },
  {
    id: "55",
    name: "Chisholm Vineyards at Adventure Farm",
    street: "1135 Clan Chisholm Ln.",
    city: "Earlysville",
    state: "VA",
    zip: "22936",
    phone: "434-971-8796",
    website: "chisholmvineyards.com",
    region: "Central Virginia"
  },
{
    id: "56",
    name: "Chiswell Farm and Winery",
    street: "430 Greenwood Rd.",
    city: "Greenwood",
    state: "VA",
    zip: "22943",
    phone: "434-252-2947",
    website: "chiswellwinery.com",
    region: "Central Virginia"
  },
  {
    id: "57",
    name: "Courthouse Creek Cidery",
    street: "1581 Maidens Rd.",
    city: "Maidens",
    state: "VA",
    zip: "23102",
    phone: "804-543-3157",
    website: "courthousecreek.com",
    region: "Central Virginia"
  },
  {
    id: "58",
    name: "Coyote Hole Craft Beverages",
    street: "225 Oak Grove Dr.",
    city: "Mineral",
    state: "VA",
    zip: "23117",
    phone: "540-894-1053",
    website: "coyotehole.com",
    region: "Central Virginia"
  },
  {
    id: "59",
    name: "Cunningham Creek Winery",
    street: "3304 Ruritan Lake Rd.",
    city: "Palmyra",
    state: "VA",
    zip: "22963",
    phone: "434-207-3907",
    website: "cunninghamcreek.wine",
    region: "Central Virginia"
  },
  {
    id: "60",
    name: "DeVault Family Vineyards",
    street: "247 Station Ln.",
    city: "Concord",
    state: "VA",
    zip: "24538",
    phone: "434-993-0722",
    website: "devaultvineyard.com",
    region: "Central Virginia"
  },
  {
    id: "61",
    name: "DuCard Vineyards",
    street: "40 Gibson Hollow Ln.",
    city: "Etlan",
    state: "VA",
    zip: "22719",
    phone: "540-923-4206",
    website: "ducardvineyards.com",
    region: "Central Virginia"
  },
  {
    id: "62",
    name: "Eagle Zen Winery",
    street: "954 Rosser Rd.",
    city: "Dillwyn",
    state: "VA",
    zip: "23936",
    phone: "757-880-7006",
    website: "eaglezenwinery.com",
    region: "Central Virginia"
  },
  {
    id: "63",
    name: "Early Mountain Vineyards",
    street: "6109 Wolftown Hood Rd.",
    city: "Madison",
    state: "VA",
    zip: "22727",
    phone: "540-948-9005",
    website: "earlymountain.com",
    region: "Central Virginia"
  },
  {
    id: "64",
    name: "Eastwood Farm and Winery",
    street: "2531 Scottsville Rd.",
    city: "Charlottesville",
    state: "VA",
    zip: "22902",
    phone: "434-264-6727",
    website: "eastwoodfarmandwinery.com",
    region: "Central Virginia"
  },
  {
    id: "65",
    name: "Elk Island Winery",
    street: "5759 River Road West",
    city: "Goochland",
    state: "VA",
    zip: "23063",
    phone: "804-627-3929",
    website: "elkislandwinery.com",
    region: "Central Virginia"
  },
  {
    id: "66",
    name: "Everleigh Vineyards",
    street: "9845 Jefferson Hwy.",
    city: "Mineral",
    state: "VA",
    zip: "23117",
    phone: "804-464-5667",
    website: "everleighvineyards.com",
    region: "Central Virginia"
  },
  {
    id: "67",
    name: "Fallen Tree Winery",
    street: "4593 Clark Rd.",
    city: "Crozet",
    state: "VA",
    zip: "22932",
    phone: "757-647-9398",
    website: "fallentreevineyard.com",
    region: "Central Virginia"
  },
  {
    id: "68",
    name: "Fifty-Third Winery and Vineyard",
    street: "13372 Shannon Hill Rd.",
    city: "Louisa",
    state: "VA",
    zip: "23093",
    phone: "540-894-1536",
    website: "53rdwinery.com",
    region: "Central Virginia"
  },
  {
    id: "69",
    name: "Flying Fox Vineyard",
    street: "10368 Critzer Shop Rd.",
    city: "Afton",
    state: "VA",
    zip: "22920",
    phone: "434-361-1692",
    website: "flyingfoxvineyard.com",
    region: "Central Virginia"
  },
  {
    id: "70",
    name: "Gabriele Rausse Winery",
    street: "3247 Carters Mountain Rd.",
    city: "Charlottesville",
    state: "VA",
    zip: "22902",
    phone: "434-981-1677",
    website: "gabrieleraussewinery.com",
    region: "Central Virginia"
  },
  {
    id: "71",
    name: "Garden Grove Brewing & Urban Winery",
    street: "3445 W. Cary St.",
    city: "Richmond",
    state: "VA",
    zip: "23221",
    phone: "804-918-6158",
    website: "gardengrovebrewing.com",
    region: "Central Virginia"
  },
  {
    id: "72",
    name: "Glass House Winery",
    street: "5898 Free Union Rd.",
    city: "Free Union",
    state: "VA",
    zip: "22940",
    phone: "434-975-0094",
    website: "glasshousewinery.com",
    region: "Central Virginia"
  },
  {
    id: "73",
    name: "Grace Estate Winery",
    street: "5273 Mount Juliet Rd.",
    city: "Crozet",
    state: "VA",
    zip: "22932",
    phone: "434-823-1486",
    website: "graceestatewinery.com",
    region: "Central Virginia"
  },
  {
    id: "74",
    name: "Grayhaven Winery",
    street: "4675 E. Grey Fox Cir.",
    city: "Gum Spring",
    state: "VA",
    zip: "23065",
    phone: "804-556-3917",
    website: "grayhavenwinery.com",
    region: "Central Virginia"
  },
  {
    id: "75",
    name: "Haley's Honey Meadery",
    street: "235 E. Broadway",
    city: "Hopewell",
    state: "VA",
    zip: "23860",
    phone: "804-668-5943",
    website: "haleyshoneymeadery.com",
    region: "Central Virginia"
  },
  {
    id: "76",
    name: "Hardware Hills Vineyard",
    street: "5199 W. River Rd.",
    city: "Scottsville",
    state: "VA",
    zip: "24590",
    phone: "434-286-4710",
    website: "hardwarehills.com",
    region: "Central Virginia"
  },
  {
    id: "77",
    name: "Hark Vineyards",
    street: "1465 Davis Shop Rd.",
    city: "Earlysville",
    state: "VA",
    zip: "22936",
    phone: "434-964-9463",
    website: "harkvineyards.com",
    region: "Central Virginia"
  },
  {
    id: "78",
    name: "Haunted Vineyards",
    street: "25231 Selma Rd.",
    city: "Jetersville",
    state: "VA",
    zip: "23083",
    phone: "804-250-1421",
    website: "hauntedvineyards.com",
    region: "Central Virginia"
  },
  {
    id: "79",
    name: "Hazy Mountain Vineyards & Brewery",
    street: "240 Hazy Mountain Ln.",
    city: "Afton",
    state: "VA",
    zip: "22920",
    phone: "540-302-2529",
    website: "hazy-mountain.com",
    region: "Central Virginia"
  },
  {
    id: "80",
    name: "Henley's Orchard Estate Cidery",
    street: "2192 Holly Hill Farm",
    city: "Crozet",
    state: "VA",
    zip: "22932",
    phone: "434-823-7848",
    website: "henleysorchard.com",
    region: "Central Virginia"
  },
  {
    id: "81",
    name: "Hill Top Berry Farm Winery & Meadery",
    street: "2800 Berry Hill Rd.",
    city: "Nellysford",
    state: "VA",
    zip: "22958",
    phone: "434-361-1266",
    website: "hilltopberrywine.com",
    region: "Central Virginia"
  },
  {
    id: "82",
    name: "Honah Lee Vineyard",
    street: "13443 Honah Lee Farm Dr.",
    city: "Gordonsville",
    state: "VA",
    zip: "22942",
    phone: "540-308-7724",
    website: "honahleevineyard.com",
    region: "Central Virginia"
  },
  {
    id: "83",
    name: "Horton Vineyards",
    street: "6399 Spotswood Tr.",
    city: "Gordonsville",
    state: "VA",
    zip: "22942",
    phone: "540-832-7440",
    website: "hortonwine.com",
    region: "Central Virginia"
  },
  {
    id: "84",
    name: "James River Cellars",
    street: "11008 Washington Hwy.",
    city: "Glen Allen",
    state: "VA",
    zip: "23059",
    phone: "804-550-7516",
    website: "jamesrivercellars.com",
    region: "Central Virginia"
  },
  {
    id: "85",
    name: "Jefferson Vineyards",
    street: "1353 Thomas Jefferson Pkwy.",
    city: "Charlottesville",
    state: "VA",
    zip: "22902",
    phone: "434-977-3042",
    website: "jeffersonvineyards.com",
    region: "Central Virginia"
  },
  {
    id: "86",
    name: "Keswick Vineyards",
    street: "1575 Keswick Winery Dr.",
    city: "Keswick",
    state: "VA",
    zip: "22947",
    phone: "434-244-3341",
    website: "keswickvineyards.com",
    region: "Central Virginia"
  },
  {
    id: "87",
    name: "King Family Vineyards",
    street: "6550 Roseland Farm",
    city: "Crozet",
    state: "VA",
    zip: "22932",
    phone: "434-823-7800",
    website: "kingfamilyvineyards.com",
    region: "Central Virginia"
  },
  {
    id: "88",
    name: "Knight's Gambit Vineyard",
    street: "218 Knole Farm Ln.",
    city: "Charlottesville",
    state: "VA",
    zip: "22901",
    phone: "434-260-9424",
    website: "knightsgambitvineyard.com",
    region: "Central Virginia"
  },
  {
    id: "89",
    name: "Lazy Days Winery",
    street: "1351 N. Amherst Hwy.",
    city: "Amherst",
    state: "VA",
    zip: "24521",
    phone: "434-381-6088",
    website: "lazydayswinery.com",
    region: "Central Virginia"
  },
  {
    id: "90",
    name: "Loving Cup Vineyard & Winery",
    street: "3340 Sutherland Rd.",
    city: "North Garden",
    state: "VA",
    zip: "22959",
    phone: "434-984-0774",
    website: "lovingcupwine.com",
    region: "Central Virginia"
  },
  {
    id: "91",
    name: "Lovingston Winery",
    street: "885 Freshwater Cove Ln.",
    city: "Lovingston",
    state: "VA",
    zip: "22949",
    phone: "434-263-8467",
    website: "lovingstonwinery.com",
    region: "Central Virginia"
  },
  {
    id: "92",
    name: "Merrie Mill Farm & Vineyard",
    street: "594 Merrie Mill Farm",
    city: "Keswick",
    state: "VA",
    zip: "22947",
    phone: "434-365-3006",
    website: "merriemillfarm.com",
    region: "Central Virginia"
  },
  {
    id: "93",
    name: "Michael Shaps Wineworks",
    street: "1650 Harris Creek Rd.",
    city: "Charlottesville",
    state: "VA",
    zip: "22902",
    phone: "434-296-3438",
    website: "michaelshapswines.com",
    region: "Central Virginia"
  },
  {
    id: "94",
    name: "Montifalco Vineyard",
    street: "1800 Fray Rd.",
    city: "Ruckersville",
    state: "VA",
    zip: "22968",
    phone: "434-989-9115",
    website: "montifalcovineyard.com",
    region: "Central Virginia"
  },
  {
    id: "95",
    name: "Moss Vineyards",
    street: "1849 Simmons Gap Rd.",
    city: "Dyke",
    state: "VA",
    zip: "22935",
    phone: "434-990-0111",
    website: "mossvineyards.net",
    region: "Central Virginia"
  },
  {
    id: "96",
    name: "Mount Alto Vineyards",
    street: "10436 Howardsville Tpke.",
    city: "Esmont",
    state: "VA",
    zip: "22937",
    phone: "804-476-0883",
    website: "mountaltovineyards.com",
    region: "Central Virginia"
  },
  {
    id: "97",
    name: "Mount Fair Vineyard",
    street: "4575 Slam Gate Rd.",
    city: "Crozet",
    state: "VA",
    zip: "22932",
    phone: "646-453-7600",
    website: "mountfairvineyard.com",
    region: "Central Virginia"
  },
  {
    id: "98",
    name: "Mountain & Vine Vineyards and Winery",
    street: "500 Delfosse Winery Ln.",
    city: "Faber",
    state: "VA",
    zip: "22938",
    phone: "434-263-6100",
    website: "delfossewine.com",
    region: "Central Virginia"
  },
  {
    id: "99",
    name: "Muddy Paws Winery",
    street: "2640 Rock Island Rd.",
    city: "Scottsville",
    state: "VA",
    zip: "24590",
    phone: "410-365-4175",
    website: "muddypawswinery.com",
    region: "Central Virginia"
  },
  {
    id: "100",
    name: "Oakencroft Farm & Winery",
    street: "1455 Oakencroft Cir.",
    city: "Charlottesville",
    state: "VA",
    zip: "22901",
    phone: "434-234-7066",
    website: "oakencroftfarm.com",
    region: "Central Virginia"
  },
  {
    id: "101",
    name: "Pippin Hill Farm & Vineyards",
    street: "5022 Plank Rd.",
    city: "North Garden",
    state: "VA",
    zip: "22959",
    phone: "434-202-8063",
    website: "pippinhillfarm.com",
    region: "Central Virginia"
  },
  {
    id: "102",
    name: "Pollak Vineyards",
    street: "330 Newtown Rd.",
    city: "Greenwood",
    state: "VA",
    zip: "22943",
    phone: "540-456-8844",
    website: "pollakvineyards.com",
    region: "Central Virginia"
  },
  {
    id: "103",
    name: "Potter's Craft Cider",
    street: "1350 Arrowhead Valley Rd.",
    city: "Charlottesville",
    state: "VA",
    zip: "22903",
    phone: "434-244-2767",
    website: "potterscraftcider.com",
    region: "Central Virginia"
  },
  {
    id: "104",
    name: "Prince Michel Vineyard",
    street: "154 Winery Ln.",
    city: "Leon",
    state: "VA",
    zip: "22725",
    phone: "800-800-9463",
    website: "princemichel.com",
    region: "Central Virginia"
  },
  {
    id: "105",
    name: "Rassawek Winery",
    street: "6276 River Road West",
    city: "Columbia",
    state: "VA",
    zip: "23038",
    phone: "804-389-1164",
    website: "rassawek.com",
    region: "Central Virginia"
  },
  {
    id: "106",
    name: "Rebec Vineyards",
    street: "2229 N. Amherst Hwy.",
    city: "Amherst",
    state: "VA",
    zip: "24521",
    phone: "434-946-5168",
    website: "rebecwinery.com",
    region: "Central Virginia"
  },
  {
    id: "107",
    name: "Reserve: Tasting Room & Lounge",
    street: "1101 Jefferson St. Ste. 100",
    city: "Lynchburg",
    state: "VA",
    zip: "24504",
    phone: "434-316-2752",
    website: "reservelbc.com",
    region: "Central Virginia"
  },
  {
    id: "108",
    name: "Revalation Vineyards",
    street: "2710 Hebron Valley Rd.",
    city: "Madison",
    state: "VA",
    zip: "22727",
    phone: "540-407-1236",
    website: "revalationvineyards.com",
    region: "Central Virginia"
  },
  {
    id: "109",
    name: "Reynard Florence Vineyard",
    street: "16109 Burnley Rd.",
    city: "Barboursville",
    state: "VA",
    zip: "22923",
    phone: "540-832-3895",
    website: "reynardflorence.com",
    region: "Central Virginia"
  },
  {
    id: "110",
    name: "River Dog Winery",
    street: "7959 Bradbury Rd.",
    city: "Henrico",
    state: "VA",
    zip: "23231",
    phone: "804-385-3770",
    website: "riverdogwinery.com",
    region: "Central Virginia"
  },
{
    id: "111",
    name: "Septenary The Winery at Seven Oaks Farm",
    street: "200 Seven Oaks Farm",
    city: "Greenwood",
    state: "VA",
    zip: "22943",
    phone: "434-996-6292",
    website: "septenarywinery.com",
    region: "Central Virginia"
  },
  {
    id: "112",
    name: "Skippers Creek Vineyard",
    street: "965 Rocky Ford Rd.",
    city: "Powhatan",
    state: "VA",
    zip: "23139",
    phone: "804-598-7291",
    website: "skipperscreekvineyard.com",
    region: "Central Virginia"
  },
  {
    id: "113",
    name: "South Paddock Winery",
    street: "6672 Blenheim Rd.",
    city: "Scottsville",
    state: "VA",
    zip: "24590",
    phone: "202-251-5291",
    website: "whitehallfarmandvineyard.com/winery",
    region: "Central Virginia"
  },
  {
    id: "114",
    name: "Southern Revere Cellars",
    street: "1100 E. Jack Jouett Rd.",
    city: "Louisa",
    state: "VA",
    zip: "23093",
    phone: "540-260-5494",
    website: "southernrevere.com",
    region: "Central Virginia"
  },
  {
    id: "115",
    name: "Southwest Mountains Vineyards",
    street: "2300 Whipper In Ln.",
    city: "Keswick",
    state: "VA",
    zip: "22947",
    phone: "434-212-3244",
    website: "smvwines.com",
    region: "Central Virginia"
  },
  {
    id: "116",
    name: "Stinson Vineyards",
    street: "4744 Sugar Hollow Rd.",
    city: "Crozet",
    state: "VA",
    zip: "22932",
    phone: "434-823-7300",
    website: "stinsonvineyards.com",
    region: "Central Virginia"
  },
  {
    id: "117",
    name: "Stone Mountain Vineyards",
    street: "1376 Wyatt Mountain Rd.",
    city: "Dyke",
    state: "VA",
    zip: "22935",
    phone: "434-990-9463",
    website: "stonemountainvineyards.com",
    region: "Central Virginia"
  },
  {
    id: "118",
    name: "Sweet Briar College Farm",
    street: "134 Chapel Rd.",
    city: "Sweet Briar",
    state: "VA",
    zip: "24595",
    phone: "434-381-0409",
    website: "sbc.edu/farm",
    region: "Central Virginia"
  },
  {
    id: "119",
    name: "Sweet Vines Farm Winery",
    street: "14376 Tower Rd.",
    city: "Unionville",
    state: "VA",
    zip: "22567",
    phone: "703-942-9336",
    website: "thevines.farm",
    region: "Central Virginia"
  },
  {
    id: "120",
    name: "Tasting Room & Taphouse at Mount Ida Reserve",
    street: "5931 Blenheim Rd.",
    city: "Charlottesville",
    state: "VA",
    zip: "24590",
    phone: "434-286-4282",
    website: "mountidareserve.com",
    region: "Central Virginia"
  },
  {
    id: "121",
    name: "Trump Winery",
    street: "385 Albemarle House Dr.",
    city: "Charlottesville",
    state: "VA",
    zip: "22902",
    phone: "434-266-9909",
    website: "trumpwinery.com",
    region: "Central Virginia"
  },
  {
    id: "122",
    name: "Valley Road Vineyards",
    street: "9264 Critzers Shop Rd. (Rt. 151)",
    city: "Afton",
    state: "VA",
    zip: "22920",
    phone: "540-456-6350",
    website: "valleyroadwines.com",
    region: "Central Virginia"
  },
  {
    id: "123",
    name: "Veritas Vineyard & Winery",
    street: "151 Veritas Ln.",
    city: "Afton",
    state: "VA",
    zip: "22920",
    phone: "540-456-8000",
    website: "veritaswines.com",
    region: "Central Virginia"
  },
  {
    id: "124",
    name: "White Hall Vineyards",
    street: "5282 Sugar Ridge Rd.",
    city: "Crozet",
    state: "VA",
    zip: "22932",
    phone: "434-823-8615",
    website: "whitehallvineyards.com",
    region: "Central Virginia"
  },
  {
    id: "125",
    name: "Wisdom Oak Winery",
    street: "3613 Walnut Branch Ln.",
    city: "North Garden",
    state: "VA",
    zip: "22959",
    phone: "434-984-4272",
    website: "wisdomoakwinery.com",
    region: "Central Virginia"
  },
  {
    id: "126",
    name: "Woodbrook Farm Vineyard",
    street: "11461 Spicers Mill Rd.",
    city: "Orange",
    state: "VA",
    zip: "22960",
    phone: "540-219-1874",
    website: "woodbrookfarmvineyard.com",
    region: "Central Virginia"
  },
  {
    id: "127",
    name: "Abingdon Vineyards",
    street: "20530 Alvarado Rd.",
    city: "Abingdon",
    state: "VA",
    zip: "24211",
    phone: "276-623-1255",
    website: "abingdonvineyards.com",
    region: "Blue Ridge"
  },
  {
    id: "128",
    name: "Beliveau Farm Winery",
    street: "3899 Eakin Farm Rd.",
    city: "Blacksburg",
    state: "VA",
    zip: "24060",
    phone: "540-961-0505",
    website: "beliveauwinery.com",
    region: "Blue Ridge"
  },
  {
    id: "129",
    name: "Chateau Morrisette Winery",
    street: "291 Winery Rd. SW",
    city: "Floyd",
    state: "VA",
    zip: "24091",
    phone: "540-593-2865",
    website: "thedogs.com",
    region: "Blue Ridge"
  },
  {
    id: "130",
    name: "Davis Valley Winery & Distillery",
    street: "1167 Davis Valley Rd.",
    city: "Rural Retreat",
    state: "VA",
    zip: "24368",
    phone: "276-686-8855",
    website: "davisvalleywinery.com",
    region: "Blue Ridge"
  },
  {
    id: "131",
    name: "Iron Heart Winery",
    street: "3742 Boone Furnace Rd.",
    city: "Allisonia",
    state: "VA",
    zip: "24347",
    phone: "540-320-0203",
    website: "ironheartwinery.com",
    region: "Blue Ridge"
  },
  {
    id: "132",
    name: "JBR Vineyards & Winery",
    street: "1360 Springdale Rd.",
    city: "Pearisburg",
    state: "VA",
    zip: "24134",
    phone: "540-250-7291",
    website: "jbrvineyards.com",
    region: "Blue Ridge"
  },
  {
    id: "133",
    name: "Nicewonder Farms & Vineyard",
    street: "22091 Nicewonder Dr.",
    city: "Bristol",
    state: "VA",
    zip: "24202",
    phone: "276-299-3260",
    website: "nicewonderfarm.com",
    region: "Blue Ridge"
  },
  {
    id: "134",
    name: "Spinning Jenny Vineyard",
    street: "2664 Old Route 100 Rd.",
    city: "Draper",
    state: "VA",
    zip: "24324",
    phone: "540-922-9829",
    website: "spinningjennyvineyard.com",
    region: "Blue Ridge"
  },
  {
    id: "135",
    name: "Squabble State Hard Cider & Spirits",
    street: "7300 Brownlow Dr.",
    city: "Bristol",
    state: "VA",
    zip: "24202",
    phone: "276-294-2196",
    website: "squabblestate.com",
    region: "Blue Ridge"
  },
  {
    id: "136",
    name: "The New River Vineyard & Winery",
    street: "6750 Falling Branch Rd.",
    city: "Fairlawn",
    state: "VA",
    zip: "24141",
    phone: "540-633-0033",
    website: "nrvwine.com",
    region: "Blue Ridge"
  },
  {
    id: "137",
    name: "Tumbling Creek Cider Company",
    street: "238 W. Main St.",
    city: "Abingdon",
    state: "VA",
    zip: "24210",
    phone: "276-451-5901",
    website: "tumblingcreekcider.com",
    region: "Blue Ridge"
  },
  {
    id: "138",
    name: "Villa Appalaccia",
    street: "752 Rock Castle Gorge Rd.",
    city: "Floyd",
    state: "VA",
    zip: "24091",
    phone: "540-593-3100",
    website: "villaappalaccia.com",
    region: "Blue Ridge"
  },
  {
    id: "139",
    name: "West Wind Farm Vineyard and Winery",
    street: "180 West Wind Dr.",
    city: "Max Meadows",
    state: "VA",
    zip: "24360",
    phone: "276-699-2020",
    website: "westwindwine.com",
    region: "Blue Ridge"
  },
  {
    id: "140",
    name: "Big Fish Cider Co.",
    street: "59 Spruce St.",
    city: "Monterey",
    state: "VA",
    zip: "24465",
    phone: "540-468-2322",
    website: "bigfishcider.com",
    region: "Virginia Mountains"
  },
  {
    id: "141",
    name: "Brooks Mill Winery",
    street: "6221 Brooks Mill Rd.",
    city: "Wirtz",
    state: "VA",
    zip: "24184",
    phone: "540-721-5215",
    website: "brooksmillwine.com",
    region: "Virginia Mountains"
  },
  {
    id: "142",
    name: "Burnbrae Vineyards",
    street: "3524 Cottontown Rd.",
    city: "Forest",
    state: "VA",
    zip: "24551",
    phone: "336-339-5634",
    website: "burnbraevineyards.com",
    region: "Virginia Mountains"
  },
  {
    id: "143",
    name: "Fables & Feathers Winery",
    street: "2117 Bruno Dr.",
    city: "Goodview",
    state: "VA",
    zip: "24095",
    phone: "540-420-0916",
    website: "fablesandfeatherswinery.com",
    region: "Virginia Mountains"
  },
  {
    id: "144",
    name: "Graham Ordinary Lodge and Meadery",
    street: "8578 Peaks Rd.",
    city: "Bedford",
    state: "VA",
    zip: "24523",
    phone: "540-986-5621",
    website: "grahamordinary.com",
    region: "Virginia Mountains"
  },
  {
    id: "145",
    name: "Hickory Hill Vineyards",
    street: "1722 Hickory Cove Ln.",
    city: "Moneta",
    state: "VA",
    zip: "24121",
    phone: "540-296-1393",
    website: "SMLwine.com",
    region: "Virginia Mountains"
  },
  {
    id: "146",
    name: "Peaks of Otter Winery & Orchards",
    street: "1218 Elmos Rd.",
    city: "Bedford",
    state: "VA",
    zip: "24523",
    phone: "540-586-3707",
    website: "peaksofotterwinery.com",
    region: "Virginia Mountains"
  },
  {
    id: "147",
    name: "Ramulose Ridge Vineyards",
    street: "3061 Hendricks Store Rd.",
    city: "Moneta",
    state: "VA",
    zip: "24121",
    phone: "540-797-6056",
    website: "ramuloseridgevineyards.com",
    region: "Virginia Mountains"
  },
  {
    id: "148",
    name: "Seven Doors Winery",
    street: "5800 Johnson Mountain Rd.",
    city: "Huddleston",
    state: "VA",
    zip: "24104",
    phone: "540-605-8745",
    website: "sevendoorswinery.com",
    region: "Virginia Mountains"
  },
  {
    id: "149",
    name: "Stoney Brook Vineyards & Winery",
    street: "516 Stoney Battery Rd.",
    city: "Troutville",
    state: "VA",
    zip: "24175",
    phone: "540-591-7089",
    website: "stoneybrookvineyards.com",
    region: "Virginia Mountains"
  },
  {
    id: "150",
    name: "Troddenvale at Oakley Farm",
    street: "170 Oakley Farm Ln.",
    city: "Warm Springs",
    state: "VA",
    zip: "24484",
    phone: "info@troddenvale.com",
    website: "troddenvale.com",
    region: "Virginia Mountains"
  },
  {
    id: "151",
    name: "Valhalla Vineyards",
    street: "6500 Mt. Chestnut Rd.",
    city: "Roanoke",
    state: "VA",
    zip: "24018",
    phone: "540-725-9463",
    website: "valhallawines.com",
    region: "Virginia Mountains"
  },
  {
    id: "152",
    name: "Virginia Mountain Vineyards",
    street: "4204 Old Fincastle Rd.",
    city: "Fincastle",
    state: "VA",
    zip: "24090",
    phone: "540-473-2979",
    website: "vmvines.com",
    region: "Virginia Mountains"
  },
  {
    id: "153",
    name: "2 Witches Winery & Brewing Co.",
    street: "209 Trade St.",
    city: "Danville",
    state: "VA",
    zip: "24541",
    phone: "434-549-2739",
    website: "2witcheswinebrew.com",
    region: "Southern Virginia"
  },
  {
    id: "154",
    name: "Altillo Vineyards",
    street: "620 Level Run Rd.",
    city: "Hurt",
    state: "VA",
    zip: "24563",
    phone: "434-324-4160",
    website: "altillovineyards.com",
    region: "Southern Virginia"
  },
  {
    id: "155",
    name: "American Way Country Wines",
    street: "13750 Hwy. 47",
    city: "Chase City",
    state: "VA",
    zip: "23924",
    phone: "434-262-1250",
    website: "americanwaycountrywines.com",
    region: "Southern Virginia"
  },
  {
    id: "156",
    name: "Bright Meadows Farm",
    street: "1181 Nathalie Rd.",
    city: "Nathalie",
    state: "VA",
    zip: "24577",
    phone: "434-349-9463",
    website: "brightmeadowsfarm.com",
    region: "Southern Virginia"
  },
  {
    id: "157",
    name: "Hamlet Vineyards",
    street: "405 Riverside Dr.",
    city: "Bassett",
    state: "VA",
    zip: "24055",
    phone: "276-629-2121",
    website: "hamletvineyards.com",
    region: "Southern Virginia"
  },
  {
    id: "158",
    name: "Hunting Creek Vineyards",
    street: "2000 Addie Williams Tr.",
    city: "Clover",
    state: "VA",
    zip: "24534",
    phone: "434-454-9219",
    website: "hcvwines.com",
    region: "Southern Virginia"
  },
  {
    id: "159",
    name: "Rosemont Vineyards",
    street: "1050 Blackridge Rd.",
    city: "La Crosse",
    state: "VA",
    zip: "23950",
    phone: "434-636-9463",
    website: "rosemontofvirginia.com",
    region: "Southern Virginia"
  },
  {
    id: "160",
    name: "The Homeplace Vineyard",
    street: "568 Rigney Cir.",
    city: "Chatham",
    state: "VA",
    zip: "24531",
    phone: "434-432-9463",
    website: "thehomeplacevineyard.com",
    region: "Southern Virginia"
  },
  {
    id: "161",
    name: "Three Sisters of Shiney Rock",
    street: "5484 Shiney Rock Rd.",
    city: "Clarksville",
    state: "VA",
    zip: "23927",
    phone: "434-298-6693",
    website: "threesistersofshineyrock.com",
    region: "Southern Virginia"
  },
  {
    id: "162",
    name: "Woodbine Vineyards",
    street: "1142 Hite Dr.",
    city: "Buffalo Junction",
    state: "VA",
    zip: "24529",
    phone: "434-222-1459",
    website: "woodbinevineyardsandwinery.com",
    region: "Southern Virginia"
  },
  {
    id: "163",
    name: "12 Ridges Vineyard",
    street: "24981 Blue Ridge Parkway",
    city: "Vesuvius",
    state: "VA",
    zip: "24483",
    phone: "434-996-4252",
    website: "12ridges.com",
    region: "Shenandoah Valley"
  },
  {
    id: "164",
    name: "Above Ground Winery",
    street: "975 McKinley Rd.",
    city: "Middlebrook",
    state: "VA",
    zip: "24459",
    phone: "540-430-4394",
    website: "agwinery.com",
    region: "Shenandoah Valley"
  },
  {
    id: "165",
    name: "Barren Ridge Vineyards",
    street: "984 Barren Ridge Rd.",
    city: "Fishersville",
    state: "VA",
    zip: "22939",
    phone: "540-248-3300",
    website: "barrenridgevineyards.com",
    region: "Shenandoah Valley"
  },
{
    id: "166",
    name: "Blue Ridge Vineyard",
    street: "1027 Shiloh Dr.",
    city: "Eagle Rock",
    state: "VA",
    zip: "24085",
    phone: "540-798-7642",
    website: "blueridgevineyard.com",
    region: "Shenandoah Valley"
  },
  {
    id: "167",
    name: "Bluestone Vineyard",
    street: "4828 Spring Creek Rd.",
    city: "Bridgewater",
    state: "VA",
    zip: "22812",
    phone: "540-828-0099",
    website: "bluestonevineyard.com",
    region: "Shenandoah Valley"
  },
  {
    id: "168",
    name: "Briedé Family Vineyards",
    street: "450 Green Spring Rd.",
    city: "Winchester",
    state: "VA",
    zip: "22603",
    phone: "540-664-2048",
    website: "briedevineyards.com",
    region: "Shenandoah Valley"
  },
  {
    id: "169",
    name: "Brix and Columns Vineyards",
    street: "1501 Dave Berry Rd.",
    city: "McGaheysville",
    state: "VA",
    zip: "22840",
    phone: "540-810-0566",
    website: "brixandcolumns.com",
    region: "Shenandoah Valley"
  },
  {
    id: "170",
    name: "Cave Ridge Vineyard",
    street: "1476 Conicville Rd.",
    city: "Mt. Jackson",
    state: "VA",
    zip: "22842",
    phone: "540-477-2585",
    website: "caveridge.com",
    region: "Shenandoah Valley"
  },
  {
    id: "171",
    name: "Ciders From Mars",
    street: "121 S. Lewis St.",
    city: "Staunton",
    state: "VA",
    zip: "24401",
    phone: "540-416-2120",
    website: "cidersfrommars.com",
    region: "Shenandoah Valley"
  },
  {
    id: "172",
    name: "Common Wealth Crush Co.",
    street: "1010 E. Main St. Ste. 110",
    city: "Waynesboro",
    state: "VA",
    zip: "22980",
    phone: "chardonel@commonwealthcrush.com",
    website: "commonwealthcrush.com",
    region: "Shenandoah Valley"
  },
  {
    id: "173",
    name: "CrossKeys Vineyards",
    street: "6011 E. Timber Ridge Rd.",
    city: "Mt. Crawford",
    state: "VA",
    zip: "22841",
    phone: "540-234-0505",
    website: "crosskeysvineyards.com",
    region: "Shenandoah Valley"
  },
  {
    id: "174",
    name: "Ecco Adesso Vineyards",
    street: "340 Ecco Adesso Ln.",
    city: "Fairfield",
    state: "VA",
    zip: "24435",
    phone: "540-817-0419",
    website: "eccoadesso.com",
    region: "Shenandoah Valley"
  },
  {
    id: "175",
    name: "Glen Manor Vineyards",
    street: "2244 Browntown Rd.",
    city: "Front Royal",
    state: "VA",
    zip: "22630",
    phone: "540-635-6324",
    website: "glenmanorvineyards.com",
    region: "Shenandoah Valley"
  },
  {
    id: "176",
    name: "Great Valley Farm Brewery & Winery",
    street: "60 Great Valley Ln.",
    city: "Natural Bridge",
    state: "VA",
    zip: "24578",
    phone: "540-521-6163",
    website: "greatvalleyfarmbrewery.com",
    region: "Shenandoah Valley"
  },
  {
    id: "177",
    name: "Halcyon Days Cider Co.",
    street: "4135 S. Lee Hwy.",
    city: "Natural Bridge",
    state: "VA",
    zip: "24578",
    phone: "540-291-1340",
    website: "halcyondayscider.com",
    region: "Shenandoah Valley"
  },
  {
    id: "178",
    name: "Hermitage Hill Cider at Stable Craft Brewing",
    street: "375 Madrid Rd.",
    city: "Waynesboro",
    state: "VA",
    zip: "22980",
    phone: "540-490-2609",
    website: "stablecraftbrewing.com",
    region: "Shenandoah Valley"
  },
  {
    id: "179",
    name: "Honey & Hops Brew Works",
    street: "212 E. Main St.",
    city: "Front Royal",
    state: "VA",
    zip: "22630",
    phone: "540-692-6032",
    website: "honeyandhopsbrewworks.com",
    region: "Shenandoah Valley"
  },
  {
    id: "180",
    name: "James Charles Winery & Vineyard",
    street: "4063 Middle Rd.",
    city: "Winchester",
    state: "VA",
    zip: "22602",
    phone: "540-931-4386",
    website: "jamescharleswine.com",
    region: "Shenandoah Valley"
  },
  {
    id: "181",
    name: "Jump Mountain Vineyard",
    street: "1493 Walkers Creek Rd.",
    city: "Rockbridge Baths",
    state: "VA",
    zip: "24473",
    phone: "540-348-6730",
    website: "jumpwines.com",
    region: "Shenandoah Valley"
  },
  {
    id: "182",
    name: "Lexington Valley Vineyard",
    street: "80 Norton Way",
    city: "Rockbridge Baths",
    state: "VA",
    zip: "24473",
    phone: "540-462-2974",
    website: "lexingtonvalleyvineyard.com",
    region: "Shenandoah Valley"
  },
  {
    id: "183",
    name: "Lightwell Survey Wines",
    street: "200 W. 12th St. Unit D53",
    city: "Waynesboro",
    state: "VA",
    zip: "22980",
    phone: "Wines@lightwellsurvey.com",
    website: "lightwellsurvey.com",
    region: "Shenandoah Valley"
  },
  {
    id: "184",
    name: "Marceline Vineyards",
    street: "5887 Cross Keys Rd.",
    city: "Mt. Crawford",
    state: "VA",
    zip: "22841",
    phone: "540-212-9798",
    website: "marcelinevineyards.com",
    region: "Shenandoah Valley"
  },
  {
    id: "185",
    name: "Misty Mountain Meadworks",
    street: "661 Warm Springs Rd.",
    city: "Winchester",
    state: "VA",
    zip: "22603",
    phone: "540-336-2273",
    website: "mistymountainmead.com",
    region: "Shenandoah Valley"
  },
  {
    id: "186",
    name: "Muse Vineyards",
    street: "16 Serendipity Ln.",
    city: "Woodstock",
    state: "VA",
    zip: "22664",
    phone: "540-459-7033",
    website: "musevineyards.com",
    region: "Shenandoah Valley"
  },
  {
    id: "187",
    name: "North Mountain Vineyard & Winery",
    street: "4374 Swartz Rd.",
    city: "Maurertown",
    state: "VA",
    zip: "22644",
    phone: "540-436-9463",
    website: "northmountainvineyard.com",
    region: "Shenandoah Valley"
  },
  {
    id: "188",
    name: "Old Hill Cider",
    street: "17768 Honeyville Rd.",
    city: "Timberville",
    state: "VA",
    zip: "22853",
    phone: "540-896-7582",
    website: "showaltersorchard.com",
    region: "Shenandoah Valley"
  },
  {
    id: "189",
    name: "Ox-Eye Vineyards",
    street: "44 Middlebrook Ave.",
    city: "Staunton",
    state: "VA",
    zip: "24401",
    phone: "540-849-7926",
    website: "oxeyevineyards.com",
    region: "Shenandoah Valley"
  },
  {
    id: "190",
    name: "Reitano Vineyards",
    street: "137 Lee Burke Rd.",
    city: "Front Royal",
    state: "VA",
    zip: "22630",
    phone: "540-550-0334",
    website: "reitanovineyards.com",
    region: "Shenandoah Valley"
  },
  {
    id: "191",
    name: "Rockbridge Vineyard & Brewery",
    street: "35 Hill View Ln.",
    city: "Raphine",
    state: "VA",
    zip: "24472",
    phone: "540-377-6204",
    website: "rockbridgevineyard.com",
    region: "Shenandoah Valley"
  },
  {
    id: "192",
    name: "Saga Meadery & Winery",
    street: "7 South St.",
    city: "Front Royal",
    state: "VA",
    zip: "22630",
    phone: "339-221-3115",
    website: "sagameadery.com",
    region: "Shenandoah Valley"
  },
  {
    id: "193",
    name: "Sage Bird Ciderworks",
    street: "325 N. Liberty St.",
    city: "Harrisonburg",
    state: "VA",
    zip: "22802",
    phone: "540-607-8084",
    website: "sagebirdciderworks.com",
    region: "Shenandoah Valley"
  },
  {
    id: "194",
    name: "Shenandoah Vineyards",
    street: "3659 S. Ox Rd.",
    city: "Edinburg",
    state: "VA",
    zip: "22824",
    phone: "540-984-8699",
    website: "shenandoahvineyardsva.com",
    region: "Shenandoah Valley"
  },
  {
    id: "195",
    name: "Star in the Valley Estate Winery",
    street: "33 Amos Ln.",
    city: "Strasburg",
    state: "VA",
    zip: "22657",
    phone: "540-514-1687",
    website: "starinthevalley.com",
    region: "Shenandoah Valley"
  },
  {
    id: "196",
    name: "Star Party",
    street: "27 W. Beverley St.",
    city: "Staunton",
    state: "VA",
    zip: "",
    phone: "540-416-2267",
    website: "starpartywinery.com",
    region: "Shenandoah Valley"
  },
  {
    id: "197",
    name: "The Winery at Kindred Pointe",
    street: "3575 Conicville Rd.",
    city: "Mt. Jackson",
    state: "VA",
    zip: "22842",
    phone: "540-477-3570",
    website: "kindredpointe.com",
    region: "Shenandoah Valley"
  },
  {
    id: "198",
    name: "Third Hill Winery at DeMello Vineyards",
    street: "2110 Quicksburg Rd.",
    city: "Quicksburg",
    state: "VA",
    zip: "22847",
    phone: "540-740-8464",
    website: "demellovineyardsthirdhillwinery.com",
    region: "Shenandoah Valley"
  },
  {
    id: "199",
    name: "Twin Oaks Tavern Winery",
    street: "18035 Raven Rocks Rd.",
    city: "Bluemont",
    state: "VA",
    zip: "20135",
    phone: "540-554-4547",
    website: "twinoakstavernwinery.com",
    region: "Shenandoah Valley"
  },
  {
    id: "200",
    name: "Valerie Hill Vineyard & Winery",
    street: "1687 Marlboro Rd.",
    city: "Stephens City",
    state: "VA",
    zip: "22655",
    phone: "540-869-9567",
    website: "valeriehillwinery.com",
    region: "Shenandoah Valley"
  },
  {
    id: "201",
    name: "Veramar Vineyard",
    street: "905 Quarry Rd.",
    city: "Berryville",
    state: "VA",
    zip: "22611",
    phone: "540-955-5510",
    website: "veramar.com",
    region: "Shenandoah Valley"
  },
  {
    id: "202",
    name: "White Oak Lavender & The Purple Wolf Vineyard",
    street: "2644 Cross Keys Rd.",
    city: "Rockingham",
    state: "VA",
    zip: "22801",
    phone: "540-421-6345",
    website: "whiteoaklavender.com",
    region: "Shenandoah Valley"
  },
  {
    id: "203",
    name: "Winchester Ciderworks",
    street: "30 E. Piccadilly St.",
    city: "Winchester",
    state: "VA",
    zip: "22601",
    phone: "540-686-7832",
    website: "winchesterciderworks.com",
    region: "Shenandoah Valley"
  },
  {
    id: "204",
    name: "Wisteria Farm & Vineyard",
    street: "1126 Marksville Rd.",
    city: "Stanley",
    state: "VA",
    zip: "22851",
    phone: "540-742-5215",
    website: "wisteriavineyard.com",
    region: "Shenandoah Valley"
  },
  {
    id: "205",
    name: "Wolf Gap Vineyard & Winery",
    street: "123 Stout Rd.",
    city: "Edinburg",
    state: "VA",
    zip: "22824",
    phone: "540-984-3306",
    website: "wolfgapvineyard.com",
    region: "Shenandoah Valley"
  },
  {
    id: "206",
    name: "50 West Vineyards",
    street: "39060 Little River Tpke.",
    city: "Middleburg",
    state: "VA",
    zip: "20117",
    phone: "571-367-4760",
    website: "50westvineyards.com",
    region: "Northern Virginia"
  },
  {
    id: "207",
    name: "8 Chains North",
    street: "38593 Daymont Ln.",
    city: "Waterford",
    state: "VA",
    zip: "20197",
    phone: "571-439-2255",
    website: "8chainsnorth.com",
    region: "Northern Virginia"
  },
  {
    id: "208",
    name: "868 Estate Vineyards",
    street: "14001 Harpers Ferry Rd.",
    city: "Hillsboro",
    state: "VA",
    zip: "20132",
    phone: "540-668-7008",
    website: "868estatevineyards.com",
    region: "Northern Virginia"
  },
  {
    id: "209",
    name: "Arterra Wines",
    street: "1808 Leeds Manor Rd.",
    city: "Delaplane",
    state: "VA",
    zip: "20144",
    phone: "540-422-3443",
    website: "arterrawines.com",
    region: "Northern Virginia"
  },
  {
    id: "210",
    name: "Aspen Dale Winery at The Barn",
    street: "11083 John Marshall Hwy.",
    city: "Delaplane",
    state: "VA",
    zip: "20144",
    phone: "540-364-1722",
    website: "aspendalewinery.com",
    region: "Northern Virginia"
  },
  {
    id: "211",
    name: "Bacchus Winery",
    street: "6320 Five Mile Centre Park",
    city: "Fredericksburg",
    state: "VA",
    zip: "22407",
    phone: "540-903-0917",
    website: "bacchusva.com",
    region: "Northern Virginia"
  },
  {
    id: "212",
    name: "Barrel Oak Winery and Brewery",
    street: "3623 Grove Ln.",
    city: "Delaplane",
    state: "VA",
    zip: "20144",
    phone: "540-364-6402",
    website: "barreloak.com",
    region: "Northern Virginia"
  },
  {
    id: "213",
    name: "Bleu Frog Vineyards",
    street: "16413 James Monroe Hwy.",
    city: "Leesburg",
    state: "VA",
    zip: "20176",
    phone: "703-297-2617",
    website: "bleufrogvineyards.com",
    region: "Northern Virginia"
  },
  {
    id: "214",
    name: "Blue Valley Vineyard and Winery",
    street: "5535 Blue Valley Way",
    city: "Delaplane",
    state: "VA",
    zip: "20144",
    phone: "540-364-2347",
    website: "bluevalleyvineyardandwinery.com",
    region: "Northern Virginia"
  },
  {
    id: "215",
    name: "Blue Wall Cider & Wine",
    street: "40614 Charles Town Pike",
    city: "Paeonian Springs",
    state: "VA",
    zip: "20129",
    phone: "540-454-2505",
    website: "bluewallcider.com",
    region: "Northern Virginia"
  },
  {
    id: "216",
    name: "Bluemont Vineyard",
    street: "18755 Foggy Bottom Rd.",
    city: "Bluemont",
    state: "VA",
    zip: "20135",
    phone: "540-554-8439",
    website: "bluemontvineyard.com",
    region: "Northern Virginia"
  },
  {
    id: "217",
    name: "Boxwood Estate Winery",
    street: "2042 Burrland Ln.",
    city: "Middleburg",
    state: "VA",
    zip: "20117",
    phone: "540-687-8778",
    website: "boxwoodwinery.com",
    region: "Northern Virginia"
  },
  {
    id: "218",
    name: "Bozzo Family Vineyards",
    street: "35226 Charles Town Pike",
    city: "Purcellville",
    state: "VA",
    zip: "20132",
    phone: "571-918-9001",
    website: "bozwines.com",
    region: "Northern Virginia"
  },
  {
    id: "219",
    name: "Breaux Vineyards",
    street: "36888 Breaux Vineyards Ln.",
    city: "Purcellville",
    state: "VA",
    zip: "20132",
    phone: "540-668-6299",
    website: "breauxvineyards.com",
    region: "Northern Virginia"
  },
  {
    id: "220",
    name: "Cana Vineyards and Winery of Middleburg",
    street: "38600 Little River Tpke.",
    city: "Middleburg",
    state: "VA",
    zip: "20117",
    phone: "703-348-2458",
    website: "canavineyards.com",
    region: "Northern Virginia"
  },
{
    id: "221",
    name: "Capstone Vineyards",
    street: "13400 Crimson Ln.",
    city: "Linden",
    state: "VA",
    zip: "22642",
    phone: "540-308-9463",
    website: "capstonevineyards.com",
    region: "Northern Virginia"
  },
  {
    id: "222",
    name: "Carriage House Wineworks",
    street: "40817 Browns Ln.",
    city: "Waterford",
    state: "VA",
    zip: "20197",
    phone: "571-239-9120",
    website: "chwwinery.com",
    region: "Northern Virginia"
  },
  {
    id: "223",
    name: "Casanel Vineyards and Winery",
    street: "17956 Canby Rd.",
    city: "Leesburg",
    state: "VA",
    zip: "20175",
    phone: "540-751-1776",
    website: "casanelvineyards.com",
    region: "Northern Virginia"
  },
  {
    id: "224",
    name: "Chateau O'Brien at Northpoint",
    street: "3238 Rail Stop Rd.",
    city: "Markham",
    state: "VA",
    zip: "22643",
    phone: "540-364-6441",
    website: "chateauobrien.com",
    region: "Northern Virginia"
  },
  {
    id: "225",
    name: "Chester Gap Cellars",
    street: "4615 Remount Rd.",
    city: "Front Royal",
    state: "VA",
    zip: "22630",
    phone: "540-636-8086",
    website: "chestergapcellars.com",
    region: "Northern Virginia"
  },
  {
    id: "226",
    name: "Chrysalis Vineyards at The Ag District",
    street: "39025 Little River Tpke.",
    city: "Middleburg",
    state: "VA",
    zip: "20117",
    phone: "540-687-8222",
    website: "chrysaliswine.com",
    region: "Northern Virginia"
  },
  {
    id: "227",
    name: "Cobbler Mountain Cellars Cidery",
    street: "5909 Long Fall Ln.",
    city: "Delaplane",
    state: "VA",
    zip: "20144",
    phone: "703-344-8610",
    website: "cobblermountain.com",
    region: "Northern Virginia"
  },
  {
    id: "228",
    name: "Corcoran Vineyards and Cider",
    street: "14635 Corkys Farm Ln.",
    city: "Waterford",
    state: "VA",
    zip: "20197",
    phone: "540-882-9073",
    website: "corcoranvineyards.com",
    region: "Northern Virginia"
  },
  {
    id: "229",
    name: "Creek's Edge Winery",
    street: "41255 Annas Ln.",
    city: "Lovettsville",
    state: "VA",
    zip: "20180",
    phone: "540-822-3825",
    website: "creeksedgewinery.com",
    region: "Northern Virginia"
  },
  {
    id: "230",
    name: "Crimson Lane Vineyards",
    street: "13334 Crimson Ln.",
    city: "Linden",
    state: "VA",
    zip: "22642",
    phone: "540-506-5062",
    website: "crimsonlanevineyards.com",
    region: "Northern Virginia"
  },
  {
    id: "231",
    name: "Crushed Cellars",
    street: "37938 Charles Town Pike",
    city: "Purcellville",
    state: "VA",
    zip: "20132",
    phone: "571-374-9463",
    website: "crushedcellars.com",
    region: "Northern Virginia"
  },
  {
    id: "232",
    name: "Delaplane Cellars",
    street: "2187 Winchester Rd.",
    city: "Delaplane",
    state: "VA",
    zip: "20144",
    phone: "540-592-7210",
    website: "delaplanecellars.com",
    region: "Northern Virginia"
  },
  {
    id: "233",
    name: "Domaine Fortier",
    street: "13235 Milltown Rd.",
    city: "Lovettsville",
    state: "VA",
    zip: "20180",
    phone: "703-870-1225",
    website: "domainefortier.com",
    region: "Northern Virginia"
  },
  {
    id: "234",
    name: "Doukénie Winery",
    street: "14727 Mountain Rd.",
    city: "Hillsboro",
    state: "VA",
    zip: "20132",
    phone: "540-668-6464",
    website: "doukeniewinery.com",
    region: "Northern Virginia"
  },
  {
    id: "235",
    name: "Eagletree Farm Vineyards",
    street: "15100 Harrison Hill Ln.",
    city: "Leesburg",
    state: "VA",
    zip: "20176",
    phone: "703-851-0699",
    website: "eagletreevineyards.com",
    region: "Northern Virginia"
  },
  {
    id: "236",
    name: "Eden Try Estate Winery",
    street: "6818 River Rd.",
    city: "Fredericksburg",
    state: "VA",
    zip: "22407",
    phone: "818-468-2936",
    website: "edentrywinery.com",
    region: "Northern Virginia"
  },
  {
    id: "237",
    name: "Effingham Manor Winery",
    street: "14325 Trotters Ridge Place",
    city: "Nokesville",
    state: "VA",
    zip: "20181",
    phone: "703-594-2300",
    website: "effinghammanor.com",
    region: "Northern Virginia"
  },
  {
    id: "238",
    name: "Endhardt Vineyards",
    street: "19600 Lincoln Rd.",
    city: "Purcellville",
    state: "VA",
    zip: "20132",
    phone: "info@ev-wine.com",
    website: "endhardtvineyards.com",
    region: "Northern Virginia"
  },
  {
    id: "239",
    name: "Fabbioli Cellars",
    street: "15669 Limestone School Rd.",
    city: "Leesburg",
    state: "VA",
    zip: "20176",
    phone: "703-771-1197",
    website: "fabbioliwines.com",
    region: "Northern Virginia"
  },
  {
    id: "240",
    name: "Firefly Cellars",
    street: "40325 Charles Town Pike",
    city: "Hamilton",
    state: "VA",
    zip: "20158",
    phone: "703-314-5650",
    website: "fireflycellars.com",
    region: "Northern Virginia"
  },
  {
    id: "241",
    name: "Fleetwood Farm Winery",
    street: "23075 Evergreen Mills Rd.",
    city: "Leesburg",
    state: "VA",
    zip: "20175",
    phone: "703-722-2124",
    website: "fleetwoodfarmwinery.com",
    region: "Northern Virginia"
  },
  {
    id: "242",
    name: "Fox Meadow Vineyards and Winery",
    street: "3310 Freezeland Rd.",
    city: "Linden",
    state: "VA",
    zip: "22642",
    phone: "540-636-6777",
    website: "foxmeadowwinery.com",
    region: "Northern Virginia"
  },
  {
    id: "243",
    name: "Gadino Cellars",
    street: "92 Schoolhouse Rd.",
    city: "Washington",
    state: "VA",
    zip: "22747",
    phone: "540-987-9292",
    website: "gadinocellars.com",
    region: "Northern Virginia"
  },
  {
    id: "244",
    name: "Good Spirit Winery",
    street: "35113 Snickersville Tpke.",
    city: "Round Hill",
    state: "VA",
    zip: "20141",
    phone: "571-479-3417",
    website: "goodspiritfarmva.com",
    region: "Northern Virginia"
  },
  {
    id: "245",
    name: "Granite Heights Winery",
    street: "8141 Opal Rd.",
    city: "Warrenton",
    state: "VA",
    zip: "20186",
    phone: "540-349-5185",
    website: "gh.wine",
    region: "Northern Virginia"
  },
  {
    id: "246",
    name: "Gray Ghost Vineyards",
    street: "14706 Lee Hwy.",
    city: "Amissville",
    state: "VA",
    zip: "20106",
    phone: "540-937-4869",
    website: "grayghostvineyards.com",
    region: "Northern Virginia"
  },
  {
    id: "247",
    name: "Greenhill Vineyards",
    street: "23595 Winery Ln.",
    city: "Middleburg",
    state: "VA",
    zip: "20117",
    phone: "540-687-6968",
    website: "experiencegreenhill.com",
    region: "Northern Virginia"
  },
  {
    id: "248",
    name: "Hidden Brook Winery",
    street: "43301 Spinks Ferry Rd.",
    city: "Leesburg",
    state: "VA",
    zip: "20176",
    phone: "703-737-3935",
    website: "hiddenbrookwinery.com",
    region: "Northern Virginia"
  },
  {
    id: "249",
    name: "Hiddencroft Vineyards",
    street: "12202 Axline Rd.",
    city: "Lovettsville",
    state: "VA",
    zip: "20180",
    phone: "540-535-5367",
    website: "hiddencroftvineyards.com",
    region: "Northern Virginia"
  },
  {
    id: "250",
    name: "Hillsborough Winery Brewery & Vineyard",
    street: "36716 Charles Town Pike",
    city: "Hillsboro",
    state: "VA",
    zip: "20132",
    phone: "540-668-6216",
    website: "hillsboroughwine.com",
    region: "Northern Virginia"
  },
  {
    id: "251",
    name: "Kalero Vineyard",
    street: "36140 Charles Town Pike",
    city: "Purcellville",
    state: "VA",
    zip: "20132",
    phone: "540-717-8118",
    website: "kalerovineyard.com",
    region: "Northern Virginia"
  },
  {
    id: "252",
    name: "Lake Anna Winery",
    street: "5621 Courthouse Rd.",
    city: "Spotsylvania",
    state: "VA",
    zip: "22551",
    phone: "540-895-5085",
    website: "lawinery.com",
    region: "Northern Virginia"
  },
  {
    id: "253",
    name: "Linden Vineyards",
    street: "3708 Harrels Corner Rd.",
    city: "Linden",
    state: "VA",
    zip: "22642",
    phone: "540-364-1997",
    website: "lindenvineyards.com",
    region: "Northern Virginia"
  },
  {
    id: "254",
    name: "Little Washington Winery and Brewery",
    street: "72 Christmas Tree Ln.",
    city: "Washington",
    state: "VA",
    zip: "22747",
    phone: "540-987-8330",
    website: "littlewashingtonwinery.com",
    region: "Northern Virginia"
  },
  {
    id: "255",
    name: "Lost Boy Cider",
    street: "317 Hooffs Run Dr.",
    city: "Alexandria",
    state: "VA",
    zip: "22314",
    phone: "703-566-5737",
    website: "lostboycider.com",
    region: "Northern Virginia"
  },
  {
    id: "256",
    name: "Magnolia Vineyards & Winery",
    street: "200 Viewtown Rd.",
    city: "Amissville",
    state: "VA",
    zip: "20106",
    phone: "703-785-8190",
    website: "magnoliavineyards.com",
    region: "Northern Virginia"
  },
  {
    id: "257",
    name: "Mattaponi Winery",
    street: "7530 Morris Rd.",
    city: "Spotsylvania Courthouse",
    state: "VA",
    zip: "22551",
    phone: "540-582-2897",
    website: "mattaponiwinery.com",
    region: "Northern Virginia"
  },
  {
    id: "258",
    name: "Mediterranean Cellars",
    street: "8295 Falcon Glen Rd.",
    city: "Warrenton",
    state: "VA",
    zip: "20186",
    phone: "540-428-1984",
    website: "mediterraneancellars.com",
    region: "Northern Virginia"
  },
  {
    id: "259",
    name: "Molon Lave Vineyards",
    street: "10075 Lees Mill Rd.",
    city: "Warrenton",
    state: "VA",
    zip: "20186",
    phone: "540-439-5460",
    website: "molonlavevineyards.com",
    region: "Northern Virginia"
  },
  {
    id: "260",
    name: "Morais Vineyards & Winery",
    street: "11409 Marsh Rd.",
    city: "Bealeton",
    state: "VA",
    zip: "22712",
    phone: "540-729-4823",
    website: "moraisvineyards.com",
    region: "Northern Virginia"
  },
  {
    id: "261",
    name: "Mountain Run Winery",
    street: "10753 Mountain Run Lake Rd.",
    city: "Culpeper",
    state: "VA",
    zip: "22701",
    phone: "703-638-5559",
    website: "mountainrunwinery.com",
    region: "Northern Virginia"
  },
  {
    id: "262",
    name: "Mt. Defiance Cider Barn",
    street: "495 E. Washington St.",
    city: "Middleburg",
    state: "VA",
    zip: "20117",
    phone: "540-883-3176",
    website: "mtdefiance.com",
    region: "Northern Virginia"
  },
  {
    id: "263",
    name: "Naked Mountain Winery and Vineyards",
    street: "2747 Leeds Manor Rd.",
    city: "Markham",
    state: "VA",
    zip: "22643",
    phone: "540-364-1609",
    website: "nakedmtnwinery.com",
    region: "Northern Virginia"
  },
  {
    id: "264",
    name: "Narmada Winery",
    street: "43 Narmada Ln.",
    city: "Amissville",
    state: "VA",
    zip: "20106",
    phone: "540-937-8215",
    website: "narmadawinery.com",
    region: "Northern Virginia"
  },
  {
    id: "265",
    name: "Nokesville Winery",
    street: "12593 Foremost Ct.",
    city: "Nokesville",
    state: "VA",
    zip: "20181",
    phone: "703-330-3467",
    website: "nokesvillewinery.com",
    region: "Northern Virginia"
  },
  {
    id: "266",
    name: "Notaviva Farm Brewery & Winery",
    street: "13274 Sagle Rd.",
    city: "Hillsboro",
    state: "VA",
    zip: "20132",
    phone: "540-668-6756",
    website: "notaviva.com",
    region: "Northern Virginia"
  },
  {
    id: "267",
    name: "October One Vineyard – Tasting Shop",
    street: "7 Loudoun St. SW",
    city: "Leesburg",
    state: "VA",
    zip: "20175",
    phone: "thepaintstripe@octoberonevineyard.com",
    website: "octoberonevineyard.com/wine-tasting-shop-leesburg/",
    region: "Northern Virginia"
  },
  {
    id: "268",
    name: "Old Farm Winery at Hartland",
    street: "23583 Fleetwood Rd.",
    city: "Aldie",
    state: "VA",
    zip: "20105",
    phone: "571-899-4380",
    website: "oldfarmwineryhartland.com",
    region: "Northern Virginia"
  },
  {
    id: "269",
    name: "Old House Vineyards",
    street: "18351 Corkys Ln.",
    city: "Culpeper",
    state: "VA",
    zip: "22701",
    phone: "540-423-1032",
    website: "oldhousetoday.com",
    region: "Northern Virginia"
  },
  {
    id: "270",
    name: "Old Trade Brewery & Cidery",
    street: "13270 Alanthus Rd.",
    city: "Brandy Station",
    state: "VA",
    zip: "22714",
    phone: "540-729-1740",
    website: "oldtradebrewery.com",
    region: "Northern Virginia"
  },
  {
    id: "271",
    name: "Otium Cellars",
    street: "18050 Tranquility Rd.",
    city: "Purcellville",
    state: "VA",
    zip: "20132",
    phone: "540-338-2027",
    website: "otiumcellars.com",
    region: "Northern Virginia"
  },
  {
    id: "272",
    name: "Paradise Springs Winery",
    street: "13219 Yates Ford Rd.",
    city: "Clifton",
    state: "VA",
    zip: "20124",
    phone: "703-830-9463",
    website: "paradisespringswinery.com",
    region: "Northern Virginia"
  },
  {
    id: "273",
    name: "Pearmund Cellars",
    street: "6190 Georgetown Rd.",
    city: "Broad Run",
    state: "VA",
    zip: "20137",
    phone: "540-347-3475",
    website: "pearmundcellars.com",
    region: "Northern Virginia"
  }
];

// Helper function to get all unique regions
export function getRegions(): string[] {
  const regions = new Set(wineries.map(w => w.region));
  return Array.from(regions).sort();
}

// Helper function to get wineries by region
export function getWineriesByRegion(region: string): Winery[] {
  return wineries.filter(w => w.region === region);
}

// Helper function to search wineries
export function searchWineries(query: string): Winery[] {
  const lowerQuery = query.toLowerCase();
  return wineries.filter(w => 
    w.name.toLowerCase().includes(lowerQuery) ||
    w.city.toLowerCase().includes(lowerQuery) ||
    w.region.toLowerCase().includes(lowerQuery)
  );
}  

